server:
  port: 9000


spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:172.17.0.2}:${DB_PORT:3306}/dog-hole?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:AX6Qjg4YRQ4kLvLB}
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.springframework.web: trace
    org.springframework.security: trace
    org.springframework.security.oauth2: debug

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

gaode:
  key: ${GAODE_KEY:111}

email:
  password: ${EMAIL_PASSWORD:111}
