spring:
  main:
    allow-circular-references: true
  application:
    name: dog-hole
  profiles:
    active: ${APP_ENV:dev}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

mybatis:
  type-aliases-package: top.alexmmd.dog.entity
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

management:
  health:
    redis:
      enabled: false
  endpoints:
    jmx:
      exposure:
        include: health,info
